# Generated by Django 2.2 on 2019-04-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMBU_Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_nombre', models.CharField(max_length=50)),
                ('sec_ubicacion', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AMBU_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_nombre_usuario', models.CharField(max_length=50)),
                ('usu_clave', models.CharField(max_length=50)),
                ('usu_nombre', models.CharField(max_length=50)),
                ('usu_apellidos', models.CharField(max_length=50)),
                ('usu_identificacion', models.CharField(max_length=50)),
            ],
        ),
    ]
