# Generated by Django 2.2 on 2019-04-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMBU_Seccionwww',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_nombre', models.CharField(max_length=50)),
                ('sec_ubicacion', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
