# Generated by Django 2.2 on 2019-04-22 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ambu_seccionwww'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AMBU_Seccionwww',
        ),
    ]
