# Generated by Django 2.2 on 2019-04-23 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ambu_solicitud_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambu_solicitud_baja',
            name='sbja_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AMBU_Usuario'),
        ),
    ]
