# Generated by Django 2.2 on 2019-04-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ambu_activo_ambu_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambu_activo',
            name='act_subestatus',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
