# Generated by Django 2.2 on 2019-04-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190425_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambu_solicitud_baja',
            name='sbja_estado_solicitud',
        ),
        migrations.RemoveField(
            model_name='ambu_solicitud_baja',
            name='sbja_usuario',
        ),
    ]
