# Generated by Django 2.2 on 2019-04-27 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190425_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambu_activo',
            old_name='act_usuario_responsabe',
            new_name='act_usuario_responsabe_id',
        ),
    ]
