# Generated by Django 2.2 on 2019-04-27 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190426_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambu_activo',
            old_name='act_usuario_responsabe_id',
            new_name='act_usuario_responsabe',
        ),
    ]
