# Generated by Django 2.2 on 2019-04-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190426_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambu_activo',
            old_name='act_calor',
            new_name='act_color',
        ),
    ]
