# Generated by Django 2.2 on 2019-04-30 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190429_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambu_activo',
            name='act_organizacion',
        ),
    ]
