# Generated by Django 2.2 on 2019-04-30 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_ambu_activo_act_organizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambu_activo',
            name='act_subestatus',
        ),
    ]
