# Generated by Django 2.2 on 2019-04-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_ambu_activo_act_subestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambu_usuario',
            name='usu_apellidos',
        ),
        migrations.RemoveField(
            model_name='ambu_usuario',
            name='usu_nombre',
        ),
        migrations.RemoveField(
            model_name='ambu_usuario',
            name='usu_nombre_usuario',
        ),
    ]
