# Generated by Django 2.2 on 2019-04-30 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190430_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMBU_Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubi_nombre', models.CharField(max_length=50)),
                ('ubi_seccion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AMBU_Seccion')),
            ],
        ),
    ]
