# Generated by Django 2.2 on 2019-04-30 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_ambu_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambu_activo',
            name='act_seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activo_seccion', to='api.AMBU_Seccion'),
        ),
        migrations.AlterField(
            model_name='ambu_ubicacion',
            name='ubi_seccion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_seccion', to='api.AMBU_Seccion'),
        ),
    ]
