# Generated by Django 2.2 on 2019-04-30 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20190430_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambu_activo',
            name='act_seccion',
        ),
        migrations.AddField(
            model_name='ambu_activo',
            name='act_ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.AMBU_Ubicacion'),
        ),
        migrations.AlterField(
            model_name='ambu_ubicacion',
            name='ubi_seccion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AMBU_Seccion'),
        ),
    ]
