# Generated by Django 2.2 on 2019-04-30 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20190430_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambu_activo',
            name='act_ubicacion',
        ),
        migrations.AddField(
            model_name='ambu_activo',
            name='act_seccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.AMBU_Seccion'),
        ),
    ]
