# Generated by Django 2.2 on 2019-04-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190430_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMBU_Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='ambu_seccion',
            name='sec_ubicacion',
        ),
        migrations.DeleteModel(
            name='AMBU_Ubicacion',
        ),
    ]
