# Generated by Django 2.2 on 2019-04-30 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190430_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambu_activo',
            name='act_seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AMBU_Seccion'),
        ),
    ]
