# Generated by Django 2.2 on 2019-04-30 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_ambu_seccion_sec_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambu_seccion',
            name='sec_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AMBU_Departamento'),
        ),
    ]
