# Generated by Django 2.2 on 2019-05-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20190430_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambu_usuario',
            name='usu_correo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
