# Generated by Django 2.2 on 2019-05-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20190430_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambu_solicitud_baja',
            name='sbja_activos',
            field=models.ManyToManyField(to='api.AMBU_Activo'),
        ),
    ]
