# Generated by Django 2.2 on 2019-05-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20190501_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambu_usuario',
            name='usu_identificacion',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
