# Generated by Django 2.2 on 2019-05-10 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20190509_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambu_solicitud_baja',
            name='sbja_usuario_nuevo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AMBU_Usuario'),
        ),
    ]
