# Generated by Django 2.2 on 2019-05-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_ambu_solicitud_baja_sbja_usuario_nuevo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambu_solicitud_baja',
            name='sbja_solicitud_traspaso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ambu_solicitud_baja',
            name='sbja_fecha_solicitud',
            field=models.DateField(auto_now=True),
        ),
    ]
