# Generated by Django 2.2 on 2019-05-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20190510_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambu_solicitud_baja',
            name='sbja_numero_formulario',
            field=models.CharField(default='g', max_length=50),
        ),
    ]
