# Generated by Django 2.2 on 2019-05-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_ambu_solicitud_baja_sbja_numero_formulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambu_solicitud_baja',
            name='sbja_numero_formulario',
            field=models.CharField(max_length=50),
        ),
    ]
