# Generated by Django 2.2 on 2019-05-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_ambu_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambu_usuario',
            name='usu_roles',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
