# Generated by Django 2.2 on 2019-05-13 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_ambu_usuario_usu_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambu_usuario',
            name='usu_roles',
        ),
        migrations.AddField(
            model_name='ambu_usuario',
            name='usu_rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.AMBU_Rol'),
            preserve_default=False,
        ),
    ]
