# Generated by Django 2.2 on 2019-05-14 17:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20190512_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambu_usuario',
            name='usu_fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ambu_usuario',
            name='usu_rol',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.AMBU_Rol'),
        ),
    ]
