# Generated by Django 2.2 on 2019-05-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_customuser_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='do',
            field=models.DateField(auto_now=True),
        ),
    ]
