# Generated by Django 2.2 on 2019-05-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20190526_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='customeQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('permiso', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='custome',
            name='permiso',
            field=models.CharField(default='', max_length=50),
        ),
    ]
