# Generated by Django 2.2 on 2019-05-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20190526_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custome',
            options={},
        ),
        migrations.AlterModelManagers(
            name='custome',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='custome',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='custome',
            name='email',
        ),
        migrations.RemoveField(
            model_name='custome',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='custome',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='custome',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='custome',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='custome',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='custome',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='custome',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='custome',
            name='password',
        ),
        migrations.RemoveField(
            model_name='custome',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='custome',
            name='username',
        ),
    ]
