# Generated by Django 2.2 on 2019-05-27 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_custome_customeq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custome',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='custome',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='customeQ',
        ),
        migrations.DeleteModel(
            name='custome',
        ),
    ]
