# Generated by Django 2.2 on 2019-05-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20190526_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='customeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('permiso', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
