# Generated by Django 2.2 on 2019-05-27 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20190527_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambu_customeusuario',
            options={},
        ),
        migrations.AlterModelManagers(
            name='ambu_customeusuario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='ambu_customeusuario',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='ambu_customeusuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ambu_customeusuario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ambu_customeusuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='ambu_customeusuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ambu_customeusuario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='ambu_customeusuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='ambu_customeusuario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='ambu_customeusuario',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='ambu_customeusuario',
            name='password',
        ),
        migrations.RemoveField(
            model_name='ambu_customeusuario',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='ambu_customeusuario',
            name='username',
        ),
    ]
