# Generated by Django 2.2 on 2019-06-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20190527_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambu_customeusuario',
            old_name='rol',
            new_name='cus_rol',
        ),
    ]
