# Generated by Django 2.2 on 2019-06-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20190603_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambu_customeusuario',
            name='cus_identificacion',
            field=models.CharField(default='', max_length=50),
        ),
    ]
