# Generated by Django 2.2 on 2019-06-03 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20190603_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambu_activo',
            name='act_usuario_responsabe',
        ),
    ]
