# Generated by Django 2.2 on 2019-06-03 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_remove_ambu_activo_act_usuario_responsabe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambu_solicitud_baja',
            name='sbja_usuario',
        ),
        migrations.RemoveField(
            model_name='ambu_solicitud_baja',
            name='sbja_usuario_nuevo',
        ),
    ]
