# Generated by Django 2.2 on 2019-06-03 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20190603_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambu_activo',
            name='act_usuario_responsabe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
