# Generated by Django 2.2 on 2019-06-03 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_ambu_activo_act_usuario_responsabe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambu_solicitud_baja',
            name='sbja_usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='entidad_usuario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambu_solicitud_baja',
            name='sbja_usuario_nuevo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
