# Generated by Django 2.2 on 2019-06-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20190603_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambu_customeusuario',
            name='cus_identificacion',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ambu_customeusuario',
            name='cus_rol',
            field=models.CharField(default='basico', max_length=50),
        ),
    ]
