# Generated by Django 2.2 on 2019-06-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20190604_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambu_customeusuario',
            name='cus_rol',
        ),
    ]
