# Generated by Django 2.2 on 2019-06-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_ambu_customeusuario_cus_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambu_activo',
            name='act_observacion',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
