# Generated by Django 2.2 on 2019-06-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20190605_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambu_activo',
            name='act_observacion',
            field=models.CharField(blank=True, default='listo', max_length=500),
            preserve_default=False,
        ),
    ]
