# Generated by Django 2.2 on 2019-06-05 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20190605_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambu_seccion',
            name='sec_departamento',
        ),
    ]
