# Generated by Django 2.2 on 2019-06-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_remove_ambu_seccion_sec_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambu_solicitud_baja',
            name='sbja_estado_solicitud',
            field=models.CharField(max_length=1),
        ),
    ]
