# Generated by Django 2.2 on 2019-06-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20190607_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambu_solicitud_baja',
            name='sbja_estado_solicitud',
            field=models.CharField(default='E', max_length=1),
        ),
    ]
