# Generated by Django 2.2 on 2019-06-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20190607_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambu_activo',
            name='act_numero_activo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
