# Generated by Django 2.2 on 2019-06-10 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20190607_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambu_customeusuario',
            name='name',
        ),
        migrations.AlterField(
            model_name='ambu_customeusuario',
            name='cus_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AMBU_Rol'),
        ),
        migrations.AlterField(
            model_name='ambu_solicitud_baja',
            name='sbja_numero_formulario',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
