# Generated by Django 2.2 on 2019-06-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20190610_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AMBU_Usuario',
        ),
    ]
